# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

version: 2
updates:
  # Keep the NuGet dependencies up to date
  - package-ecosystem: "nuget"
    directory: "/ZeroBounceSDK/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "nuget dependencies"
    groups:
      nuget:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/ZeroBounceTests/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "nuget dependencies"
    groups:
      nuget:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/ZeroBounceSample/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "nuget dependencies"
    groups:
      nuget:
        applies-to: version-updates
        patterns:
          - "*"

  # Keep the Github Actions dependencies up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "github dependencies"
    groups:
      github:
        applies-to: version-updates
        patterns:
          - "*"
